# Generated by Django 5.2.5 on 2025-09-23 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('coordination', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('condition', models.JSONField(default=dict)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warn', 'Warn'), ('critical', 'Critical')], default='warn', max_length=16)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_alert_rules', to='accounts.userprofile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('current_value', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('ack', 'Acknowledged'), ('closed', 'Closed')], default='open', max_length=16)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_events', to='projects.project')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_events', to='coordination.coordinationrun')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='risks.alertrule')),
            ],
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_type', models.CharField(max_length=60)),
                ('risk_score', models.DecimalField(decimal_places=3, max_digits=6)),
                ('recommendation', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='projects.project')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='coordination.coordinationrun')),
            ],
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['project'], name='idx_rule_project'),
        ),
        migrations.AddIndex(
            model_name='alertevent',
            index=models.Index(fields=['project', 'triggered_at'], name='idx_event_project_time'),
        ),
        migrations.AddIndex(
            model_name='alertevent',
            index=models.Index(fields=['status'], name='idx_event_status'),
        ),
        migrations.AddIndex(
            model_name='riskassessment',
            index=models.Index(fields=['project', 'risk_score'], name='idx_risk_proj_score'),
        ),
        migrations.AddConstraint(
            model_name='riskassessment',
            constraint=models.UniqueConstraint(fields=('project', 'run', 'risk_type'), name='uq_risk'),
        ),
    ]
