# Generated by Django 5.2.5 on 2025-09-16 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.EmailField(blank=True, help_text='Preferred contact email (defaults to account email)', max_length=254, verbose_name='Contact Email')),
                ('first_name', models.CharField(blank=True, help_text='User given name stored on profile', max_length=150, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, help_text='User family name stored on profile', max_length=150, verbose_name='Last name')),
                ('username', models.CharField(blank=True, help_text='Auto-generated from first and last name', max_length=150, verbose_name='Profile Username')),
                ('avatar', models.ImageField(blank=True, help_text="User's profile picture", null=True, upload_to='avatars/', verbose_name='Avatar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
