# Generated by Django 5.2.5 on 2025-09-29 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True, help_text='Home address for service delivery'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number for service bookings', max_length=20),
        ),
        migrations.DeleteModel(
            name='GitCredential',
        ),
    ]
