# Generated by Django 5.2.5 on 2025-09-24 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_type', models.CharField(choices=[('https_token', 'HTTPS Personal Access Token'), ('ssh_key', 'SSH Private Key'), ('basic_auth', 'Username/Password')], default='https_token', max_length=20)),
                ('provider', models.CharField(default='github', help_text='Git provider (github, gitlab, bitbucket, etc.)', max_length=50)),
                ('encrypted_data', models.TextField(help_text='Encrypted credential data (token, username/password, ssh key)')),
                ('username', models.CharField(blank=True, help_text='Username for basic auth or git user', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='git_credentials', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'Git Credential',
                'verbose_name_plural': 'Git Credentials',
                'unique_together': {('user_profile', 'provider', 'credential_type')},
            },
        ),
    ]
