# Generated by Django 5.2.5 on 2025-08-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_userprofile_bio_remove_userprofile_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, help_text='User given name stored on profile', max_length=150, verbose_name='First name'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, help_text='User family name stored on profile', max_length=150, verbose_name='Last name'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(blank=True, help_text='Auto-generated from first and last name', max_length=150, verbose_name='Profile Username'),
        ),
    ]
