# Generated by Django 5.2.5 on 2025-09-16 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('repo_url', models.URLField(max_length=255, unique=True)),
                ('default_branch', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_projects', to='accounts.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('maintainer', 'Maintainer'), ('reviewer', 'Reviewer'), ('member', 'Member')], default='member', max_length=40)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to='accounts.userprofile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='projects.project')),
            ],
            options={
                'indexes': [models.Index(fields=['project', 'role'], name='idx_member_project_role')],
                'constraints': [models.UniqueConstraint(fields=('project', 'profile'), name='uq_project_member')],
            },
        ),
    ]
