# Generated by Django 5.2.5 on 2025-09-23 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='projectmember',
            name='uq_project_member',
        ),
        migrations.RenameIndex(
            model_name='projectmember',
            new_name='projects_pr_project_5b8833_idx',
            old_name='idx_member_project_role',
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('maintainer', 'Maintainer'), ('reviewer', 'Reviewer')], default='reviewer', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='projectmember',
            unique_together={('project', 'profile')},
        ),
    ]
