# Generated by Django 5.2.5 on 2025-09-16 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TnmJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_url', models.CharField(max_length=500)),
                ('branch', models.CharField(max_length=100)),
                ('command', models.CharField(max_length=120)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('args', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], db_index=True, default='queued', max_length=24)),
                ('error', models.TextField(blank=True, null=True)),
                ('stdout_url', models.CharField(blank=True, max_length=800, null=True)),
                ('stderr_url', models.CharField(blank=True, max_length=800, null=True)),
                ('result_url', models.CharField(blank=True, max_length=800, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_tnm_jobs', to='accounts.userprofile')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tnm_jobs', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='MatrixChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matrix_name', models.CharField(max_length=120)),
                ('chunk_no', models.IntegerField()),
                ('data', models.JSONField(default=list)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matrix_chunks', to='tnm_integration.tnmjob')),
            ],
        ),
        migrations.CreateModel(
            name='JsonPayload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('payload', models.JSONField(default=dict)),
                ('schema_version', models.CharField(blank=True, max_length=50, null=True)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='json_payloads', to='tnm_integration.tnmjob')),
            ],
        ),
        migrations.CreateModel(
            name='JobArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_type', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=800)),
                ('checksum', models.CharField(blank=True, max_length=200, null=True)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='tnm_integration.tnmjob')),
            ],
        ),
        migrations.AddIndex(
            model_name='tnmjob',
            index=models.Index(fields=['project', 'status', 'updated_at'], name='idx_job_project_status_time'),
        ),
        migrations.AddIndex(
            model_name='tnmjob',
            index=models.Index(fields=['command', 'updated_at'], name='idx_job_command_time'),
        ),
        migrations.AddIndex(
            model_name='matrixchunk',
            index=models.Index(fields=['job', 'matrix_name', 'chunk_no'], name='idx_matrix_lookup'),
        ),
        migrations.AddConstraint(
            model_name='matrixchunk',
            constraint=models.UniqueConstraint(fields=('job', 'matrix_name', 'chunk_no'), name='uq_matrix_chunk'),
        ),
        migrations.AddConstraint(
            model_name='jsonpayload',
            constraint=models.UniqueConstraint(fields=('job', 'name'), name='uq_jsonpayload'),
        ),
        migrations.AddIndex(
            model_name='jobartifact',
            index=models.Index(fields=['job', 'artifact_type'], name='idx_artifact_job_type'),
        ),
        migrations.AddConstraint(
            model_name='jobartifact',
            constraint=models.UniqueConstraint(fields=('job', 'name'), name='uq_jobartifact'),
        ),
    ]
