# Generated by Django 5.2.5 on 2025-08-28 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TnmJob',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('repo_url', models.URLField()),
                ('branch', models.CharField(default='main', max_length=255)),
                ('command', models.CharField(max_length=255)),
                ('options', models.JSONField(blank=True, default=list)),
                ('args', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], db_index=True, default='queued', max_length=16)),
                ('stdout_url', models.URLField(blank=True, default='')),
                ('stderr_url', models.URLField(blank=True, default='')),
                ('result_url', models.URLField(blank=True, default='')),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tnm_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
