# Generated by Django 5.2.5 on 2025-09-23 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_login', models.CharField(max_length=191, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('affiliation', models.CharField(blank=True, max_length=191, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['github_login'], name='idx_contrib_login')],
            },
        ),
        migrations.CreateModel(
            name='CodeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('language', models.CharField(blank=True, max_length=40, null=True)),
                ('loc', models.IntegerField(blank=True, null=True)),
                ('last_modified_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_files', to='projects.project')),
            ],
            options={
                'indexes': [models.Index(fields=['project', 'language'], name='idx_codefile_proj_lang')],
                'constraints': [models.UniqueConstraint(fields=('project', 'path'), name='uq_codefile_project_path')],
            },
        ),
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha', models.CharField(max_length=64)),
                ('authored_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='projects.project')),
                ('author_contributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_commits', to='contributors.contributor')),
            ],
            options={
                'indexes': [models.Index(fields=['project', 'authored_at'], name='idx_commit_project_time')],
                'constraints': [models.UniqueConstraint(fields=('project', 'sha'), name='uq_commit_sha')],
            },
        ),
        migrations.CreateModel(
            name='ProjectContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commits_count', models.IntegerField(default=0)),
                ('last_active_at', models.DateTimeField(blank=True, null=True)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='contributors.contributor')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to='projects.project')),
            ],
            options={
                'indexes': [models.Index(fields=['project', 'commits_count'], name='idx_proj_contrib_stats')],
                'constraints': [models.UniqueConstraint(fields=('project', 'contributor'), name='uq_proj_contrib')],
            },
        ),
    ]
