# Generated by Django 5.2.5 on 2025-09-24 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_login', models.CharField(max_length=191, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('full_name', models.CharField(blank=True, help_text='Full name of contributor (user can add)', max_length=200, null=True)),
                ('affiliation', models.CharField(blank=True, max_length=191, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['github_login'], name='idx_contrib_login')],
            },
        ),
        migrations.CreateModel(
            name='CodeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('language', models.CharField(blank=True, max_length=40, null=True)),
                ('loc', models.IntegerField(blank=True, null=True)),
                ('last_modified_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_files', to='projects.project')),
            ],
            options={
                'indexes': [models.Index(fields=['project', 'language'], name='idx_codefile_proj_lang')],
                'constraints': [models.UniqueConstraint(fields=('project', 'path'), name='uq_codefile_project_path')],
            },
        ),
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha', models.CharField(max_length=64)),
                ('authored_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='projects.project')),
                ('author_contributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_commits', to='contributors.contributor')),
            ],
            options={
                'indexes': [models.Index(fields=['project', 'authored_at'], name='idx_commit_project_time')],
                'constraints': [models.UniqueConstraint(fields=('project', 'sha'), name='uq_commit_sha')],
            },
        ),
        migrations.CreateModel(
            name='ProjectContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commits_count', models.IntegerField(default=0)),
                ('last_active_at', models.DateTimeField(blank=True, null=True)),
                ('tnm_user_id', models.CharField(blank=True, help_text='User ID from TNM analysis', max_length=50, null=True)),
                ('files_modified', models.IntegerField(default=0, help_text='Number of files modified')),
                ('total_modifications', models.IntegerField(default=0, help_text='Total modifications across all files')),
                ('avg_modifications_per_file', models.FloatField(default=0.0, help_text='Average modifications per file')),
                ('functional_role', models.CharField(choices=[('coder', 'Coder'), ('reviewer', 'Reviewer'), ('unclassified', 'Unclassified')], default='unclassified', help_text='Functional role for MC-STC calculation', max_length=20)),
                ('is_core_contributor', models.BooleanField(default=False, help_text='Is this a core contributor')),
                ('role_confidence', models.FloatField(default=0.0, help_text='Confidence score for role classification (0-1)')),
                ('last_tnm_analysis', models.DateTimeField(blank=True, help_text='Last TNM analysis timestamp', null=True)),
                ('tnm_branch', models.CharField(blank=True, help_text='Branch analyzed by TNM', max_length=100)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='contributors.contributor')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to='projects.project')),
            ],
            options={
                'indexes': [models.Index(fields=['project', 'commits_count'], name='idx_proj_contrib_stats'), models.Index(fields=['project', 'functional_role'], name='idx_proj_contrib_role'), models.Index(fields=['project', 'total_modifications'], name='idx_proj_contrib_mods'), models.Index(fields=['project', 'is_core_contributor'], name='idx_proj_contrib_core')],
                'constraints': [models.UniqueConstraint(fields=('project', 'contributor'), name='uq_proj_contrib')],
            },
        ),
    ]
