# Generated by Django 5.2.5 on 2025-09-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0001_initial'),
        ('projects', '0002_remove_projectmember_uq_project_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcontributor',
            name='avg_modifications_per_file',
            field=models.FloatField(default=0.0, help_text='Average modifications per file'),
        ),
        migrations.AddField(
            model_name='projectcontributor',
            name='files_modified',
            field=models.IntegerField(default=0, help_text='Number of files modified'),
        ),
        migrations.AddField(
            model_name='projectcontributor',
            name='functional_role',
            field=models.CharField(choices=[('architect', 'Architect'), ('core_developer', 'Core Developer'), ('domain_expert', 'Domain Expert'), ('reviewer', 'Reviewer'), ('occasional', 'Occasional Contributor'), ('tester', 'Tester'), ('documentation', 'Documentation Writer'), ('unclassified', 'Unclassified')], default='unclassified', help_text='Functional role for MC-STC calculation', max_length=20),
        ),
        migrations.AddField(
            model_name='projectcontributor',
            name='is_core_contributor',
            field=models.BooleanField(default=False, help_text='Is this a core contributor'),
        ),
        migrations.AddField(
            model_name='projectcontributor',
            name='last_tnm_analysis',
            field=models.DateTimeField(blank=True, help_text='Last TNM analysis timestamp', null=True),
        ),
        migrations.AddField(
            model_name='projectcontributor',
            name='role_confidence',
            field=models.FloatField(default=0.0, help_text='Confidence score for role classification (0-1)'),
        ),
        migrations.AddField(
            model_name='projectcontributor',
            name='tnm_branch',
            field=models.CharField(blank=True, help_text='Branch analyzed by TNM', max_length=100),
        ),
        migrations.AddField(
            model_name='projectcontributor',
            name='tnm_user_id',
            field=models.CharField(blank=True, help_text='User ID from TNM analysis', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projectcontributor',
            name='total_modifications',
            field=models.IntegerField(default=0, help_text='Total modifications across all files'),
        ),
        migrations.AddIndex(
            model_name='projectcontributor',
            index=models.Index(fields=['project', 'functional_role'], name='idx_proj_contrib_role'),
        ),
        migrations.AddIndex(
            model_name='projectcontributor',
            index=models.Index(fields=['project', 'total_modifications'], name='idx_proj_contrib_mods'),
        ),
        migrations.AddIndex(
            model_name='projectcontributor',
            index=models.Index(fields=['project', 'is_core_contributor'], name='idx_proj_contrib_core'),
        ),
    ]
