# Generated by Django 5.2.5 on 2025-09-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0002_projectcontributor_avg_modifications_per_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='first_name',
            field=models.CharField(blank=True, help_text='First name of contributor', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contributor',
            name='last_name',
            field=models.CharField(blank=True, help_text='Last name of contributor', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='projectcontributor',
            name='functional_role',
            field=models.CharField(choices=[('coder', 'Coder'), ('reviewer', 'Reviewer'), ('unclassified', 'Unclassified')], default='unclassified', help_text='Functional role for MC-STC calculation', max_length=20),
        ),
    ]
