# Generated by Django 5.2.5 on 2025-09-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0003_contributor_first_name_contributor_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='contributor',
            name='last_name',
        ),
        migrations.AddField(
            model_name='contributor',
            name='full_name',
            field=models.CharField(blank=True, help_text='Full name of contributor (user can add)', max_length=200, null=True),
        ),
    ]
